/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as SplatIndexRouteImport } from './routes/$/index'
import { Route as DashboardSettingsRouteRouteImport } from './routes/dashboard/settings/route'
import { Route as DashboardSettingsIndexRouteImport } from './routes/dashboard/settings/index'
import { Route as AuthSignupIndexRouteImport } from './routes/auth/signup/index'
import { Route as AuthSigninIndexRouteImport } from './routes/auth/signin/index'
import { Route as AuthForgotPasswordIndexRouteImport } from './routes/auth/forgot-password/index'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo/start.server-funcs'
import { Route as DemoStartApiRequestRouteImport } from './routes/demo/start.api-request'
import { Route as DemoApiNamesRouteImport } from './routes/demo/api.names'
import { Route as DemoStartSsrIndexRouteImport } from './routes/demo/start.ssr.index'
import { Route as DashboardSettingsSecurityIndexRouteImport } from './routes/dashboard/settings/security/index'
import { Route as DashboardSettingsProfileIndexRouteImport } from './routes/dashboard/settings/profile/index'
import { Route as DashboardSettingsNotificationsIndexRouteImport } from './routes/dashboard/settings/notifications/index'
import { Route as DashboardSettingsManageCardsIndexRouteImport } from './routes/dashboard/settings/manage-cards/index'
import { Route as DashboardExpendituresViewIndexRouteImport } from './routes/dashboard/expenditures/view/index'
import { Route as DashboardExpendituresBulkUploadIndexRouteImport } from './routes/dashboard/expenditures/bulk-upload/index'
import { Route as DashboardExpendituresAddIndexRouteImport } from './routes/dashboard/expenditures/add/index'
import { Route as DemoStartSsrSpaModeRouteImport } from './routes/demo/start.ssr.spa-mode'
import { Route as DemoStartSsrFullSsrRouteImport } from './routes/demo/start.ssr.full-ssr'
import { Route as DemoStartSsrDataOnlyRouteImport } from './routes/demo/start.ssr.data-only'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const SplatIndexRoute = SplatIndexRouteImport.update({
  id: '/$/',
  path: '/$/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRouteRoute = DashboardSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSettingsIndexRoute = DashboardSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardSettingsRouteRoute,
} as any)
const AuthSignupIndexRoute = AuthSignupIndexRouteImport.update({
  id: '/signup/',
  path: '/signup/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSigninIndexRoute = AuthSigninIndexRouteImport.update({
  id: '/signin/',
  path: '/signin/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthForgotPasswordIndexRoute = AuthForgotPasswordIndexRouteImport.update({
  id: '/forgot-password/',
  path: '/forgot-password/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiNamesRoute = DemoApiNamesRouteImport.update({
  id: '/demo/api/names',
  path: '/demo/api/names',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrIndexRoute = DemoStartSsrIndexRouteImport.update({
  id: '/demo/start/ssr/',
  path: '/demo/start/ssr/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsSecurityIndexRoute =
  DashboardSettingsSecurityIndexRouteImport.update({
    id: '/security/',
    path: '/security/',
    getParentRoute: () => DashboardSettingsRouteRoute,
  } as any)
const DashboardSettingsProfileIndexRoute =
  DashboardSettingsProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => DashboardSettingsRouteRoute,
  } as any)
const DashboardSettingsNotificationsIndexRoute =
  DashboardSettingsNotificationsIndexRouteImport.update({
    id: '/notifications/',
    path: '/notifications/',
    getParentRoute: () => DashboardSettingsRouteRoute,
  } as any)
const DashboardSettingsManageCardsIndexRoute =
  DashboardSettingsManageCardsIndexRouteImport.update({
    id: '/manage-cards/',
    path: '/manage-cards/',
    getParentRoute: () => DashboardSettingsRouteRoute,
  } as any)
const DashboardExpendituresViewIndexRoute =
  DashboardExpendituresViewIndexRouteImport.update({
    id: '/expenditures/view/',
    path: '/expenditures/view/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardExpendituresBulkUploadIndexRoute =
  DashboardExpendituresBulkUploadIndexRouteImport.update({
    id: '/expenditures/bulk-upload/',
    path: '/expenditures/bulk-upload/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardExpendituresAddIndexRoute =
  DashboardExpendituresAddIndexRouteImport.update({
    id: '/expenditures/add/',
    path: '/expenditures/add/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DemoStartSsrSpaModeRoute = DemoStartSsrSpaModeRouteImport.update({
  id: '/demo/start/ssr/spa-mode',
  path: '/demo/start/ssr/spa-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrFullSsrRoute = DemoStartSsrFullSsrRouteImport.update({
  id: '/demo/start/ssr/full-ssr',
  path: '/demo/start/ssr/full-ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrDataOnlyRoute = DemoStartSsrDataOnlyRouteImport.update({
  id: '/demo/start/ssr/data-only',
  path: '/demo/start/ssr/data-only',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRouteRouteWithChildren
  '/$': typeof SplatIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordIndexRoute
  '/auth/signin': typeof AuthSigninIndexRoute
  '/auth/signup': typeof AuthSignupIndexRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/dashboard/expenditures/add': typeof DashboardExpendituresAddIndexRoute
  '/dashboard/expenditures/bulk-upload': typeof DashboardExpendituresBulkUploadIndexRoute
  '/dashboard/expenditures/view': typeof DashboardExpendituresViewIndexRoute
  '/dashboard/settings/manage-cards': typeof DashboardSettingsManageCardsIndexRoute
  '/dashboard/settings/notifications': typeof DashboardSettingsNotificationsIndexRoute
  '/dashboard/settings/profile': typeof DashboardSettingsProfileIndexRoute
  '/dashboard/settings/security': typeof DashboardSettingsSecurityIndexRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/$': typeof SplatIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordIndexRoute
  '/auth/signin': typeof AuthSigninIndexRoute
  '/auth/signup': typeof AuthSignupIndexRoute
  '/dashboard/settings': typeof DashboardSettingsIndexRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/dashboard/expenditures/add': typeof DashboardExpendituresAddIndexRoute
  '/dashboard/expenditures/bulk-upload': typeof DashboardExpendituresBulkUploadIndexRoute
  '/dashboard/expenditures/view': typeof DashboardExpendituresViewIndexRoute
  '/dashboard/settings/manage-cards': typeof DashboardSettingsManageCardsIndexRoute
  '/dashboard/settings/notifications': typeof DashboardSettingsNotificationsIndexRoute
  '/dashboard/settings/profile': typeof DashboardSettingsProfileIndexRoute
  '/dashboard/settings/security': typeof DashboardSettingsSecurityIndexRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRouteRouteWithChildren
  '/$/': typeof SplatIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/auth/forgot-password/': typeof AuthForgotPasswordIndexRoute
  '/auth/signin/': typeof AuthSigninIndexRoute
  '/auth/signup/': typeof AuthSignupIndexRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/dashboard/expenditures/add/': typeof DashboardExpendituresAddIndexRoute
  '/dashboard/expenditures/bulk-upload/': typeof DashboardExpendituresBulkUploadIndexRoute
  '/dashboard/expenditures/view/': typeof DashboardExpendituresViewIndexRoute
  '/dashboard/settings/manage-cards/': typeof DashboardSettingsManageCardsIndexRoute
  '/dashboard/settings/notifications/': typeof DashboardSettingsNotificationsIndexRoute
  '/dashboard/settings/profile/': typeof DashboardSettingsProfileIndexRoute
  '/dashboard/settings/security/': typeof DashboardSettingsSecurityIndexRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/dashboard/settings'
    | '/$'
    | '/dashboard/'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/auth/forgot-password'
    | '/auth/signin'
    | '/auth/signup'
    | '/dashboard/settings/'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/dashboard/expenditures/add'
    | '/dashboard/expenditures/bulk-upload'
    | '/dashboard/expenditures/view'
    | '/dashboard/settings/manage-cards'
    | '/dashboard/settings/notifications'
    | '/dashboard/settings/profile'
    | '/dashboard/settings/security'
    | '/demo/start/ssr'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/$'
    | '/dashboard'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/auth/forgot-password'
    | '/auth/signin'
    | '/auth/signup'
    | '/dashboard/settings'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/dashboard/expenditures/add'
    | '/dashboard/expenditures/bulk-upload'
    | '/dashboard/expenditures/view'
    | '/dashboard/settings/manage-cards'
    | '/dashboard/settings/notifications'
    | '/dashboard/settings/profile'
    | '/dashboard/settings/security'
    | '/demo/start/ssr'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/dashboard/settings'
    | '/$/'
    | '/dashboard/'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/auth/forgot-password/'
    | '/auth/signin/'
    | '/auth/signup/'
    | '/dashboard/settings/'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/dashboard/expenditures/add/'
    | '/dashboard/expenditures/bulk-upload/'
    | '/dashboard/expenditures/view/'
    | '/dashboard/settings/manage-cards/'
    | '/dashboard/settings/notifications/'
    | '/dashboard/settings/profile/'
    | '/dashboard/settings/security/'
    | '/demo/start/ssr/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  SplatIndexRoute: typeof SplatIndexRoute
  DemoApiNamesRoute: typeof DemoApiNamesRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
  DemoStartSsrDataOnlyRoute: typeof DemoStartSsrDataOnlyRoute
  DemoStartSsrFullSsrRoute: typeof DemoStartSsrFullSsrRoute
  DemoStartSsrSpaModeRoute: typeof DemoStartSsrSpaModeRoute
  DemoStartSsrIndexRoute: typeof DemoStartSsrIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/$/': {
      id: '/$/'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings/': {
      id: '/dashboard/settings/'
      path: '/'
      fullPath: '/dashboard/settings/'
      preLoaderRoute: typeof DashboardSettingsIndexRouteImport
      parentRoute: typeof DashboardSettingsRouteRoute
    }
    '/auth/signup/': {
      id: '/auth/signup/'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/signin/': {
      id: '/auth/signin/'
      path: '/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof AuthSigninIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/forgot-password/': {
      id: '/auth/forgot-password/'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/names': {
      id: '/demo/api/names'
      path: '/demo/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof DemoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/': {
      id: '/demo/start/ssr/'
      path: '/demo/start/ssr'
      fullPath: '/demo/start/ssr'
      preLoaderRoute: typeof DemoStartSsrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings/security/': {
      id: '/dashboard/settings/security/'
      path: '/security'
      fullPath: '/dashboard/settings/security'
      preLoaderRoute: typeof DashboardSettingsSecurityIndexRouteImport
      parentRoute: typeof DashboardSettingsRouteRoute
    }
    '/dashboard/settings/profile/': {
      id: '/dashboard/settings/profile/'
      path: '/profile'
      fullPath: '/dashboard/settings/profile'
      preLoaderRoute: typeof DashboardSettingsProfileIndexRouteImport
      parentRoute: typeof DashboardSettingsRouteRoute
    }
    '/dashboard/settings/notifications/': {
      id: '/dashboard/settings/notifications/'
      path: '/notifications'
      fullPath: '/dashboard/settings/notifications'
      preLoaderRoute: typeof DashboardSettingsNotificationsIndexRouteImport
      parentRoute: typeof DashboardSettingsRouteRoute
    }
    '/dashboard/settings/manage-cards/': {
      id: '/dashboard/settings/manage-cards/'
      path: '/manage-cards'
      fullPath: '/dashboard/settings/manage-cards'
      preLoaderRoute: typeof DashboardSettingsManageCardsIndexRouteImport
      parentRoute: typeof DashboardSettingsRouteRoute
    }
    '/dashboard/expenditures/view/': {
      id: '/dashboard/expenditures/view/'
      path: '/expenditures/view'
      fullPath: '/dashboard/expenditures/view'
      preLoaderRoute: typeof DashboardExpendituresViewIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/expenditures/bulk-upload/': {
      id: '/dashboard/expenditures/bulk-upload/'
      path: '/expenditures/bulk-upload'
      fullPath: '/dashboard/expenditures/bulk-upload'
      preLoaderRoute: typeof DashboardExpendituresBulkUploadIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/expenditures/add/': {
      id: '/dashboard/expenditures/add/'
      path: '/expenditures/add'
      fullPath: '/dashboard/expenditures/add'
      preLoaderRoute: typeof DashboardExpendituresAddIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/demo/start/ssr/spa-mode': {
      id: '/demo/start/ssr/spa-mode'
      path: '/demo/start/ssr/spa-mode'
      fullPath: '/demo/start/ssr/spa-mode'
      preLoaderRoute: typeof DemoStartSsrSpaModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/full-ssr': {
      id: '/demo/start/ssr/full-ssr'
      path: '/demo/start/ssr/full-ssr'
      fullPath: '/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof DemoStartSsrFullSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/data-only': {
      id: '/demo/start/ssr/data-only'
      path: '/demo/start/ssr/data-only'
      fullPath: '/demo/start/ssr/data-only'
      preLoaderRoute: typeof DemoStartSsrDataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteRouteChildren {
  AuthForgotPasswordIndexRoute: typeof AuthForgotPasswordIndexRoute
  AuthSigninIndexRoute: typeof AuthSigninIndexRoute
  AuthSignupIndexRoute: typeof AuthSignupIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgotPasswordIndexRoute: AuthForgotPasswordIndexRoute,
  AuthSigninIndexRoute: AuthSigninIndexRoute,
  AuthSignupIndexRoute: AuthSignupIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface DashboardSettingsRouteRouteChildren {
  DashboardSettingsIndexRoute: typeof DashboardSettingsIndexRoute
  DashboardSettingsManageCardsIndexRoute: typeof DashboardSettingsManageCardsIndexRoute
  DashboardSettingsNotificationsIndexRoute: typeof DashboardSettingsNotificationsIndexRoute
  DashboardSettingsProfileIndexRoute: typeof DashboardSettingsProfileIndexRoute
  DashboardSettingsSecurityIndexRoute: typeof DashboardSettingsSecurityIndexRoute
}

const DashboardSettingsRouteRouteChildren: DashboardSettingsRouteRouteChildren =
  {
    DashboardSettingsIndexRoute: DashboardSettingsIndexRoute,
    DashboardSettingsManageCardsIndexRoute:
      DashboardSettingsManageCardsIndexRoute,
    DashboardSettingsNotificationsIndexRoute:
      DashboardSettingsNotificationsIndexRoute,
    DashboardSettingsProfileIndexRoute: DashboardSettingsProfileIndexRoute,
    DashboardSettingsSecurityIndexRoute: DashboardSettingsSecurityIndexRoute,
  }

const DashboardSettingsRouteRouteWithChildren =
  DashboardSettingsRouteRoute._addFileChildren(
    DashboardSettingsRouteRouteChildren,
  )

interface DashboardRouteRouteChildren {
  DashboardSettingsRouteRoute: typeof DashboardSettingsRouteRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardExpendituresAddIndexRoute: typeof DashboardExpendituresAddIndexRoute
  DashboardExpendituresBulkUploadIndexRoute: typeof DashboardExpendituresBulkUploadIndexRoute
  DashboardExpendituresViewIndexRoute: typeof DashboardExpendituresViewIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardSettingsRouteRoute: DashboardSettingsRouteRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardExpendituresAddIndexRoute: DashboardExpendituresAddIndexRoute,
  DashboardExpendituresBulkUploadIndexRoute:
    DashboardExpendituresBulkUploadIndexRoute,
  DashboardExpendituresViewIndexRoute: DashboardExpendituresViewIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  SplatIndexRoute: SplatIndexRoute,
  DemoApiNamesRoute: DemoApiNamesRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
  DemoStartSsrDataOnlyRoute: DemoStartSsrDataOnlyRoute,
  DemoStartSsrFullSsrRoute: DemoStartSsrFullSsrRoute,
  DemoStartSsrSpaModeRoute: DemoStartSsrSpaModeRoute,
  DemoStartSsrIndexRoute: DemoStartSsrIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
