/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteRouteImport } from './routes/settings/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as SplatIndexRouteImport } from './routes/$/index'
import { Route as SettingsSecurityIndexRouteImport } from './routes/settings/security/index'
import { Route as SettingsProfileIndexRouteImport } from './routes/settings/profile/index'
import { Route as SettingsNotificationsIndexRouteImport } from './routes/settings/notifications/index'
import { Route as ExpendituresViewIndexRouteImport } from './routes/expenditures/view/index'
import { Route as ExpendituresBulkUploadIndexRouteImport } from './routes/expenditures/bulk-upload/index'
import { Route as ExpendituresAddIndexRouteImport } from './routes/expenditures/add/index'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo/start.server-funcs'
import { Route as DemoStartApiRequestRouteImport } from './routes/demo/start.api-request'
import { Route as DemoApiNamesRouteImport } from './routes/demo/api.names'
import { Route as DemoStartSsrIndexRouteImport } from './routes/demo/start.ssr.index'
import { Route as DemoStartSsrSpaModeRouteImport } from './routes/demo/start.ssr.spa-mode'
import { Route as DemoStartSsrFullSsrRouteImport } from './routes/demo/start.ssr.full-ssr'
import { Route as DemoStartSsrDataOnlyRouteImport } from './routes/demo/start.ssr.data-only'

const SettingsRouteRoute = SettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatIndexRoute = SplatIndexRouteImport.update({
  id: '/$/',
  path: '/$/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSecurityIndexRoute = SettingsSecurityIndexRouteImport.update({
  id: '/security/',
  path: '/security/',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsProfileIndexRoute = SettingsProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsNotificationsIndexRoute =
  SettingsNotificationsIndexRouteImport.update({
    id: '/notifications/',
    path: '/notifications/',
    getParentRoute: () => SettingsRouteRoute,
  } as any)
const ExpendituresViewIndexRoute = ExpendituresViewIndexRouteImport.update({
  id: '/expenditures/view/',
  path: '/expenditures/view/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpendituresBulkUploadIndexRoute =
  ExpendituresBulkUploadIndexRouteImport.update({
    id: '/expenditures/bulk-upload/',
    path: '/expenditures/bulk-upload/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ExpendituresAddIndexRoute = ExpendituresAddIndexRouteImport.update({
  id: '/expenditures/add/',
  path: '/expenditures/add/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiNamesRoute = DemoApiNamesRouteImport.update({
  id: '/demo/api/names',
  path: '/demo/api/names',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrIndexRoute = DemoStartSsrIndexRouteImport.update({
  id: '/demo/start/ssr/',
  path: '/demo/start/ssr/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrSpaModeRoute = DemoStartSsrSpaModeRouteImport.update({
  id: '/demo/start/ssr/spa-mode',
  path: '/demo/start/ssr/spa-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrFullSsrRoute = DemoStartSsrFullSsrRouteImport.update({
  id: '/demo/start/ssr/full-ssr',
  path: '/demo/start/ssr/full-ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrDataOnlyRoute = DemoStartSsrDataOnlyRouteImport.update({
  id: '/demo/start/ssr/data-only',
  path: '/demo/start/ssr/data-only',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteRouteWithChildren
  '/$': typeof SplatIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/expenditures/add': typeof ExpendituresAddIndexRoute
  '/expenditures/bulk-upload': typeof ExpendituresBulkUploadIndexRoute
  '/expenditures/view': typeof ExpendituresViewIndexRoute
  '/settings/notifications': typeof SettingsNotificationsIndexRoute
  '/settings/profile': typeof SettingsProfileIndexRoute
  '/settings/security': typeof SettingsSecurityIndexRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/expenditures/add': typeof ExpendituresAddIndexRoute
  '/expenditures/bulk-upload': typeof ExpendituresBulkUploadIndexRoute
  '/expenditures/view': typeof ExpendituresViewIndexRoute
  '/settings/notifications': typeof SettingsNotificationsIndexRoute
  '/settings/profile': typeof SettingsProfileIndexRoute
  '/settings/security': typeof SettingsSecurityIndexRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteRouteWithChildren
  '/$/': typeof SplatIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/expenditures/add/': typeof ExpendituresAddIndexRoute
  '/expenditures/bulk-upload/': typeof ExpendituresBulkUploadIndexRoute
  '/expenditures/view/': typeof ExpendituresViewIndexRoute
  '/settings/notifications/': typeof SettingsNotificationsIndexRoute
  '/settings/profile/': typeof SettingsProfileIndexRoute
  '/settings/security/': typeof SettingsSecurityIndexRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/$'
    | '/dashboard'
    | '/settings/'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/expenditures/add'
    | '/expenditures/bulk-upload'
    | '/expenditures/view'
    | '/settings/notifications'
    | '/settings/profile'
    | '/settings/security'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/dashboard'
    | '/settings'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/expenditures/add'
    | '/expenditures/bulk-upload'
    | '/expenditures/view'
    | '/settings/notifications'
    | '/settings/profile'
    | '/settings/security'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/$/'
    | '/dashboard/'
    | '/settings/'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/expenditures/add/'
    | '/expenditures/bulk-upload/'
    | '/expenditures/view/'
    | '/settings/notifications/'
    | '/settings/profile/'
    | '/settings/security/'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRouteRoute: typeof SettingsRouteRouteWithChildren
  SplatIndexRoute: typeof SplatIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DemoApiNamesRoute: typeof DemoApiNamesRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
  ExpendituresAddIndexRoute: typeof ExpendituresAddIndexRoute
  ExpendituresBulkUploadIndexRoute: typeof ExpendituresBulkUploadIndexRoute
  ExpendituresViewIndexRoute: typeof ExpendituresViewIndexRoute
  DemoStartSsrDataOnlyRoute: typeof DemoStartSsrDataOnlyRoute
  DemoStartSsrFullSsrRoute: typeof DemoStartSsrFullSsrRoute
  DemoStartSsrSpaModeRoute: typeof DemoStartSsrSpaModeRoute
  DemoStartSsrIndexRoute: typeof DemoStartSsrIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$/': {
      id: '/$/'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/security/': {
      id: '/settings/security/'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof SettingsSecurityIndexRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/profile/': {
      id: '/settings/profile/'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileIndexRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/notifications/': {
      id: '/settings/notifications/'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof SettingsNotificationsIndexRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/expenditures/view/': {
      id: '/expenditures/view/'
      path: '/expenditures/view'
      fullPath: '/expenditures/view'
      preLoaderRoute: typeof ExpendituresViewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenditures/bulk-upload/': {
      id: '/expenditures/bulk-upload/'
      path: '/expenditures/bulk-upload'
      fullPath: '/expenditures/bulk-upload'
      preLoaderRoute: typeof ExpendituresBulkUploadIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenditures/add/': {
      id: '/expenditures/add/'
      path: '/expenditures/add'
      fullPath: '/expenditures/add'
      preLoaderRoute: typeof ExpendituresAddIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/names': {
      id: '/demo/api/names'
      path: '/demo/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof DemoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/': {
      id: '/demo/start/ssr/'
      path: '/demo/start/ssr'
      fullPath: '/demo/start/ssr'
      preLoaderRoute: typeof DemoStartSsrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/spa-mode': {
      id: '/demo/start/ssr/spa-mode'
      path: '/demo/start/ssr/spa-mode'
      fullPath: '/demo/start/ssr/spa-mode'
      preLoaderRoute: typeof DemoStartSsrSpaModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/full-ssr': {
      id: '/demo/start/ssr/full-ssr'
      path: '/demo/start/ssr/full-ssr'
      fullPath: '/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof DemoStartSsrFullSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/data-only': {
      id: '/demo/start/ssr/data-only'
      path: '/demo/start/ssr/data-only'
      fullPath: '/demo/start/ssr/data-only'
      preLoaderRoute: typeof DemoStartSsrDataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SettingsRouteRouteChildren {
  SettingsIndexRoute: typeof SettingsIndexRoute
  SettingsNotificationsIndexRoute: typeof SettingsNotificationsIndexRoute
  SettingsProfileIndexRoute: typeof SettingsProfileIndexRoute
  SettingsSecurityIndexRoute: typeof SettingsSecurityIndexRoute
}

const SettingsRouteRouteChildren: SettingsRouteRouteChildren = {
  SettingsIndexRoute: SettingsIndexRoute,
  SettingsNotificationsIndexRoute: SettingsNotificationsIndexRoute,
  SettingsProfileIndexRoute: SettingsProfileIndexRoute,
  SettingsSecurityIndexRoute: SettingsSecurityIndexRoute,
}

const SettingsRouteRouteWithChildren = SettingsRouteRoute._addFileChildren(
  SettingsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRouteRoute: SettingsRouteRouteWithChildren,
  SplatIndexRoute: SplatIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DemoApiNamesRoute: DemoApiNamesRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
  ExpendituresAddIndexRoute: ExpendituresAddIndexRoute,
  ExpendituresBulkUploadIndexRoute: ExpendituresBulkUploadIndexRoute,
  ExpendituresViewIndexRoute: ExpendituresViewIndexRoute,
  DemoStartSsrDataOnlyRoute: DemoStartSsrDataOnlyRoute,
  DemoStartSsrFullSsrRoute: DemoStartSsrFullSsrRoute,
  DemoStartSsrSpaModeRoute: DemoStartSsrSpaModeRoute,
  DemoStartSsrIndexRoute: DemoStartSsrIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
